/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdminHeader: typeof import('./components/layout/AdminHeader.vue')['default']
    AdminLayout: typeof import('./components/layout/AdminLayout.vue')['default']
    ArticleCard: typeof import('./components/article/ArticleCard.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    Footer: typeof import('./components/layout/Footer.vue')['default']
    Header: typeof import('./components/layout/Header.vue')['default']
    LanguageSwitch: typeof import('./components/common/LanguageSwitch.vue')['default']
    Loading: typeof import('./components/common/Loading.vue')['default']
    MainLayout: typeof import('./components/layout/MainLayout.vue')['default']
    PageHeader: typeof import('./components/common/PageHeader.vue')['default']
    RichTextEditor: typeof import('./components/editor/RichTextEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/layout/Sidebar.vue')['default']
    ThemeSwitch: typeof import('./components/common/ThemeSwitch.vue')['default']
  }
}
